networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.2:v1.15.1
        gid: '1000'
        uid: '1000'
        username: leon
      context: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/db-build
      dockerfile: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-sw6350-db
    environment:
      COLUMNS: '161'
      DDEV_PROJECT: sw6350
      LINES: '47'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      timeout: 2m
    hostname: sw6350-db
    image: drud/ddev-dbserver-mariadb-10.2:v1.15.1-sw6350-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0
      com.ddev.platform: ddev
      com.ddev.site-name: sw6350
    ports:
    - 127.0.0.1:32768:3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: 1000:1000
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-sw6350-dba
    environment:
      HTTPS_EXPOSE: 8037:8036
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: db
      PMA_USER: db
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: sw6350.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: sw6350-dba
    image: phpmyadmin/phpmyadmin:5
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0
      com.ddev.platform: ddev
      com.ddev.site-name: sw6350
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.15.3
        gid: '1000'
        uid: '1000'
        username: leon
      context: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/web-build
      dockerfile: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-sw6350-web
    environment:
      COLUMNS: '161'
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: https://sw6350.ddev.site
      DDEV_PROJECT: sw6350
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: sw6350
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: public
      DRUSH_OPTIONS_URI: https://sw6350.ddev.site
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTPS_EXPOSE: 443:80,8026:8025
      HTTP_EXPOSE: 80:80,8025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '47'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: sw6350.ddev.site
    external_links:
    - ddev-router:sw6350.ddev.site
    extra_hosts:
    - host.docker.internal:172.17.0.1
    healthcheck:
      interval: 1s
      retries: 20
      start_period: 20s
      timeout: 2m
    hostname: sw6350-web
    image: drud/ddev-webserver:v1.15.3-sw6350-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0
      com.ddev.platform: ddev
      com.ddev.site-name: sw6350
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0
      target: /var/www/html
      type: bind
    - /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev:/mnt/ddev_config:ro
    - /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - /home/leon/htdocs/git/Shopware6PluginTester/shopware/6.3.5.0/.ddev/apache:/etc/apache2/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: sw6350-mariadb

